### PR TITLE
Only build turbostat and sst on x86

### PR DESCRIPTION
**Pull request by rafaelfolco**
Ignore otherwise.

### CODE REVIEW

**Review by k-rister — COMMENTED** [review]
Shouldn't this be doing some kind of architecture check and only building it on an x86 one?

As it is it appears like it will try to build, fail, and then just continue anyway.  That wastes time on non x86 architectures and will miss errors on x86.

**Comment by rafaelfolco** [comment]
> Shouldn't this be doing some kind of architecture check and only building it on an x86 one?
> 
> As it is it appears like it will try to build, fail, and then just continue anyway. That wastes time on non x86 architectures and will miss errors on x86.

I'll try to find a better solution that checks arch.

**Comment by k-rister** [comment]
> > Shouldn't this be doing some kind of architecture check and only building it on an x86 one?
> > As it is it appears like it will try to build, fail, and then just continue anyway. That wastes time on non x86 architectures and will miss errors on x86.
> 
> I'll try to find a better solution that checks arch.

Can it not be something simple like:

```
if [ "${uname -m)" == "x86_64" ]; then <do stuff>; fi
```

**Comment by atheurer** [comment]
the `if [ "${uname -m)" == "x86_64" ]` is probably fine, but it makes me wonder if we eventually need arch-specific subsections in the workshop json schema

**Comment by k-rister** [comment]
> the `if [ "${uname -m)" == "x86_64" ]` is probably fine, but it makes me wonder if we eventually need arch-specific subsections in the workshop json schema

I think it's definitely something worth exploring.  The suggestion I made that you reference was just a near term hack to work around this.

**Comment by k-rister** [comment]
This is being handled by https://github.com/perftool-incubator/tool-kernel/pull/30 now.

**Pull request closed without merging**
